[package]
name = "echosphere"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = "2.8.4"
openzeppelin = { git = "https://github.com/openzeppelin/cairo-contracts", tag = "v0.18.0" }
alexandria_storage = { git = "https://github.com/keep-starknet-strange/alexandria.git", tag = "cairo-v2.3.0-rc0" }


[dev-dependencies]
snforge_std = "0.36.0"
# assert_macros = "2.8.4"

[[target.starknet-contract]]
casm = true

[scripts]
test = "snforge test"
